============================= test session starts ==============================
platform darwin -- Python 3.11.0, pytest-8.3.5, pluggy-1.5.0
rootdir: /Users/MikeWolf/Projects/YeshieHead
plugins: anyio-4.8.0, langsmith-0.3.42, asyncio-0.26.0
asyncio: mode=Mode.STRICT, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
collected 17 items

tests/e2e/command_execution/test_stepper_commands.py .......FFFFFFFFFF   [100%]

=================================== FAILURES ===================================
____________________________ test_scrollto_command _____________________________

stepper_page = <async_generator object stepper_page at 0x103b72d40>

    @pytest.mark.asyncio
    async def test_scrollto_command(stepper_page):
        async for page in stepper_page:
>           result = await page.evaluate("cmd => Stepper(cmd)", "scrollto #btn")

tests/e2e/command_execution/test_stepper_commands.py:140: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Python/3.11/lib/python/site-packages/playwright/async_api/_generated.py:8513: in evaluate
    await self._impl_obj.evaluate(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_page.py:468: in evaluate
    return await self._main_frame.evaluate(expression, arg)
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_frame.py:278: in evaluate
    await self._channel.send(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Connection object at 0x10450a110>
cb = <function Channel.send.<locals>.<lambda> at 0x10425b6a0>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.evaluate: Error: Invalid command
E               at window.Stepper (<anonymous>:60:13)
E               at eval (eval at evaluate (:313:29), <anonymous>:1:8)
E               at UtilityScript.evaluate (<anonymous>:320:18)
E               at UtilityScript.<anonymous> (<anonymous>:1:44)

../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:528: Error
______________________________ test_hover_command ______________________________

stepper_page = <async_generator object stepper_page at 0x103fa7040>

    @pytest.mark.asyncio
    async def test_hover_command(stepper_page):
        async for page in stepper_page:
>           result = await page.evaluate("cmd => Stepper(cmd)", "hover #btn")

tests/e2e/command_execution/test_stepper_commands.py:147: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Python/3.11/lib/python/site-packages/playwright/async_api/_generated.py:8513: in evaluate
    await self._impl_obj.evaluate(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_page.py:468: in evaluate
    return await self._main_frame.evaluate(expression, arg)
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_frame.py:278: in evaluate
    await self._channel.send(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Connection object at 0x103bb5f50>
cb = <function Channel.send.<locals>.<lambda> at 0x104540e00>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.evaluate: Error: Invalid command
E               at window.Stepper (<anonymous>:60:13)
E               at eval (eval at evaluate (:313:29), <anonymous>:1:8)
E               at UtilityScript.evaluate (<anonymous>:320:18)
E               at UtilityScript.<anonymous> (<anonymous>:1:44)

../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:528: Error
__________________________ test_getattribute_command ___________________________

stepper_page = <async_generator object stepper_page at 0x103fa6240>

    @pytest.mark.asyncio
    async def test_getattribute_command(stepper_page):
        async for page in stepper_page:
>           result = await page.evaluate("cmd => Stepper(cmd)", "getattribute #link href")

tests/e2e/command_execution/test_stepper_commands.py:154: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Python/3.11/lib/python/site-packages/playwright/async_api/_generated.py:8513: in evaluate
    await self._impl_obj.evaluate(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_page.py:468: in evaluate
    return await self._main_frame.evaluate(expression, arg)
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_frame.py:278: in evaluate
    await self._channel.send(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Connection object at 0x103c4c290>
cb = <function Channel.send.<locals>.<lambda> at 0x103fa98a0>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.evaluate: Error: Invalid command
E               at window.Stepper (<anonymous>:60:13)
E               at eval (eval at evaluate (:313:29), <anonymous>:1:8)
E               at UtilityScript.evaluate (<anonymous>:320:18)
E               at UtilityScript.<anonymous> (<anonymous>:1:44)

../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:528: Error
________________________ test_getcomputedstyle_command _________________________

stepper_page = <async_generator object stepper_page at 0x103fa4640>

    @pytest.mark.asyncio
    async def test_getcomputedstyle_command(stepper_page):
        async for page in stepper_page:
>           result = await page.evaluate("cmd => Stepper(cmd)", "getcomputedstyle #btn color")

tests/e2e/command_execution/test_stepper_commands.py:161: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Python/3.11/lib/python/site-packages/playwright/async_api/_generated.py:8513: in evaluate
    await self._impl_obj.evaluate(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_page.py:468: in evaluate
    return await self._main_frame.evaluate(expression, arg)
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_frame.py:278: in evaluate
    await self._channel.send(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Connection object at 0x105809450>
cb = <function Channel.send.<locals>.<lambda> at 0x103c0f420>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.evaluate: Error: Invalid command
E               at window.Stepper (<anonymous>:60:13)
E               at eval (eval at evaluate (:313:29), <anonymous>:1:8)
E               at UtilityScript.evaluate (<anonymous>:320:18)
E               at UtilityScript.<anonymous> (<anonymous>:1:44)

../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:528: Error
__________________________ test_waitfor_command_quiet __________________________

stepper_page = <async_generator object stepper_page at 0x103fa7640>

    @pytest.mark.asyncio
    async def test_waitfor_command_quiet(stepper_page):
        async for page in stepper_page:
>           result = await page.evaluate("cmd => Stepper(cmd)", "waitfor quiet 100")

tests/e2e/command_execution/test_stepper_commands.py:168: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Python/3.11/lib/python/site-packages/playwright/async_api/_generated.py:8513: in evaluate
    await self._impl_obj.evaluate(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_page.py:468: in evaluate
    return await self._main_frame.evaluate(expression, arg)
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_frame.py:278: in evaluate
    await self._channel.send(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Connection object at 0x10450aed0>
cb = <function Channel.send.<locals>.<lambda> at 0x1042d3a60>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.evaluate: Error: Invalid command
E               at window.Stepper (<anonymous>:60:13)
E               at eval (eval at evaluate (:313:29), <anonymous>:1:8)
E               at UtilityScript.evaluate (<anonymous>:320:18)
E               at UtilityScript.<anonymous> (<anonymous>:1:44)

../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:528: Error
______________________________ test_wait_command _______________________________

stepper_page = <async_generator object stepper_page at 0x103fa4840>

    @pytest.mark.asyncio
    async def test_wait_command(stepper_page):
        async for page in stepper_page:
>           result = await page.evaluate("cmd => Stepper(cmd)", "wait 10")

tests/e2e/command_execution/test_stepper_commands.py:175: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Python/3.11/lib/python/site-packages/playwright/async_api/_generated.py:8513: in evaluate
    await self._impl_obj.evaluate(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_page.py:468: in evaluate
    return await self._main_frame.evaluate(expression, arg)
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_frame.py:278: in evaluate
    await self._channel.send(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Connection object at 0x10426f950>
cb = <function Channel.send.<locals>.<lambda> at 0x1040196c0>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.evaluate: Error: Invalid command
E               at window.Stepper (<anonymous>:60:13)
E               at eval (eval at evaluate (:313:29), <anonymous>:1:8)
E               at UtilityScript.evaluate (<anonymous>:320:18)
E               at UtilityScript.<anonymous> (<anonymous>:1:44)

../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:528: Error
____________________________ test_executejs_command ____________________________

stepper_page = <async_generator object stepper_page at 0x103fa6640>

    @pytest.mark.asyncio
    async def test_executejs_command(stepper_page):
        async for page in stepper_page:
>           result = await page.evaluate("cmd => Stepper(cmd)", "executejs 2+2")

tests/e2e/command_execution/test_stepper_commands.py:182: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Python/3.11/lib/python/site-packages/playwright/async_api/_generated.py:8513: in evaluate
    await self._impl_obj.evaluate(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_page.py:468: in evaluate
    return await self._main_frame.evaluate(expression, arg)
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_frame.py:278: in evaluate
    await self._channel.send(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Connection object at 0x104547210>
cb = <function Channel.send.<locals>.<lambda> at 0x1042b32e0>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.evaluate: Error: Invalid command
E               at window.Stepper (<anonymous>:60:13)
E               at eval (eval at evaluate (:313:29), <anonymous>:1:8)
E               at UtilityScript.evaluate (<anonymous>:320:18)
E               at UtilityScript.<anonymous> (<anonymous>:1:44)

../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:528: Error
_____________________________ test_changes_on_off ______________________________

stepper_page = <async_generator object stepper_page at 0x103fa7140>

    @pytest.mark.asyncio
    async def test_changes_on_off(stepper_page):
        async for page in stepper_page:
>           result_on = await page.evaluate("cmd => Stepper(cmd)", "changes on")

tests/e2e/command_execution/test_stepper_commands.py:189: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Python/3.11/lib/python/site-packages/playwright/async_api/_generated.py:8513: in evaluate
    await self._impl_obj.evaluate(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_page.py:468: in evaluate
    return await self._main_frame.evaluate(expression, arg)
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_frame.py:278: in evaluate
    await self._channel.send(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Connection object at 0x103f72250>
cb = <function Channel.send.<locals>.<lambda> at 0x10425aac0>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.evaluate: Error: Invalid command
E               at window.Stepper (<anonymous>:60:13)
E               at eval (eval at evaluate (:313:29), <anonymous>:1:8)
E               at UtilityScript.evaluate (<anonymous>:320:18)
E               at UtilityScript.<anonymous> (<anonymous>:1:44)

../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:528: Error
_____________________________ test_message_command _____________________________

stepper_page = <async_generator object stepper_page at 0x103fa6440>

    @pytest.mark.asyncio
    async def test_message_command(stepper_page):
        async for page in stepper_page:
>           result = await page.evaluate("cmd => Stepper(cmd)", "message \"Hello\"")

tests/e2e/command_execution/test_stepper_commands.py:198: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Python/3.11/lib/python/site-packages/playwright/async_api/_generated.py:8513: in evaluate
    await self._impl_obj.evaluate(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_page.py:468: in evaluate
    return await self._main_frame.evaluate(expression, arg)
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_frame.py:278: in evaluate
    await self._channel.send(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Connection object at 0x103c3f1d0>
cb = <function Channel.send.<locals>.<lambda> at 0x104234220>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.evaluate: Error: Invalid command
E               at window.Stepper (<anonymous>:60:13)
E               at eval (eval at evaluate (:313:29), <anonymous>:1:8)
E               at UtilityScript.evaluate (<anonymous>:320:18)
E               at UtilityScript.<anonymous> (<anonymous>:1:44)

../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:528: Error
_______________________ test_asserttextcontains_command ________________________

stepper_page = <async_generator object stepper_page at 0x103fa5f40>

    @pytest.mark.asyncio
    async def test_asserttextcontains_command(stepper_page):
        async for page in stepper_page:
            await page.evaluate("cmd => Stepper(cmd)", "click #btn")
>           result = await page.evaluate("cmd => Stepper(cmd)", "asserttextcontains #status \"clicked\"")

tests/e2e/command_execution/test_stepper_commands.py:206: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Python/3.11/lib/python/site-packages/playwright/async_api/_generated.py:8513: in evaluate
    await self._impl_obj.evaluate(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_page.py:468: in evaluate
    return await self._main_frame.evaluate(expression, arg)
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_frame.py:278: in evaluate
    await self._channel.send(
../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Connection object at 0x104023290>
cb = <function Channel.send.<locals>.<lambda> at 0x104540cc0>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.evaluate: Error: Invalid command
E               at window.Stepper (<anonymous>:60:13)
E               at eval (eval at evaluate (:313:29), <anonymous>:1:8)
E               at UtilityScript.evaluate (<anonymous>:320:18)
E               at UtilityScript.<anonymous> (<anonymous>:1:44)

../../Library/Python/3.11/lib/python/site-packages/playwright/_impl/_connection.py:528: Error
=============================== warnings summary ===============================
tests/e2e/command_execution/test_stepper_commands.py:6
  /Users/MikeWolf/Projects/YeshieHead/tests/e2e/command_execution/test_stepper_commands.py:6: DeprecationWarning: invalid escape sequence '\s'
    STEPPER_JS = """

tests/e2e/command_execution/test_stepper_commands.py::test_navto_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:884: DeprecationWarning: The event_loop fixture provided by pytest-asyncio has been redefined in
  /Users/MikeWolf/Projects/YeshieHead/tests/conftest.py:57
  Replacing the event_loop fixture with a custom implementation is deprecated
  and will lead to errors in the future.
  If you want to request an asyncio event loop with a scope other than function
  scope, use the "loop_scope" argument to the asyncio mark when marking the tests.
  If you want to return different types of event loops, use the event_loop_policy
  fixture.
  
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_navto_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_navto_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_click_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_click_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_type_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_type_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_waitforelement_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_waitforelement_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_click_invalid_selector
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_click_invalid_selector' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_invalid_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_invalid_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_waitforelement_timeout
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_waitforelement_timeout' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_scrollto_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_scrollto_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_hover_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_hover_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_getattribute_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_getattribute_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_getcomputedstyle_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_getcomputedstyle_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_waitfor_command_quiet
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_waitfor_command_quiet' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_wait_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_wait_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_executejs_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_executejs_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_changes_on_off
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_changes_on_off' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_message_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_message_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/e2e/command_execution/test_stepper_commands.py::test_asserttextcontains_command
  /Users/MikeWolf/Library/Python/3.11/lib/python/site-packages/pytest_asyncio/plugin.py:1019: PytestDeprecationWarning: asyncio test 'test_asserttextcontains_command' requested async @pytest.fixture 'stepper_page' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/e2e/command_execution/test_stepper_commands.py::test_scrollto_command
FAILED tests/e2e/command_execution/test_stepper_commands.py::test_hover_command
FAILED tests/e2e/command_execution/test_stepper_commands.py::test_getattribute_command
FAILED tests/e2e/command_execution/test_stepper_commands.py::test_getcomputedstyle_command
FAILED tests/e2e/command_execution/test_stepper_commands.py::test_waitfor_command_quiet
FAILED tests/e2e/command_execution/test_stepper_commands.py::test_wait_command
FAILED tests/e2e/command_execution/test_stepper_commands.py::test_executejs_command
FAILED tests/e2e/command_execution/test_stepper_commands.py::test_changes_on_off
FAILED tests/e2e/command_execution/test_stepper_commands.py::test_message_command
FAILED tests/e2e/command_execution/test_stepper_commands.py::test_asserttextcontains_command
================== 10 failed, 7 passed, 19 warnings in 6.93s ===================
